### PR TITLE
add default value to fix build with only suffix option for Qt

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**

### CODE REVIEW

**Comment by cchampet** [comment]
I don't know why Travis did not update the status of your last commit...
But there is an error : 
```
In file included from app/LoudnessValidator/AudioFile.cpp:1:0:
app/LoudnessValidator/AudioFile.h:4:23: fatal error: QtGui/QtGui: No such file or directory
 #include <QtGui/QtGui>
                       ^
compilation terminated.
In file included from app/LoudnessValidator/DropAudio.cpp:1:0:
app/LoudnessValidator/DropAudio.h:4:23: fatal error: QtGui/QtGui: No such file or directory
 #include <QtGui/QtGui>
                       ^
compilation terminated.
scons: *** [build/release/app/LoudnessValidator/AudioFile.o] Error 1
scons: *** [build/release/app/LoudnessValidator/DropAudio.o] Error 1
scons: building terminated because of errors.
```

**Comment by MarcAntoine-Arnaud** [comment]
last commit: 611a68c4c9f86ca05dd79dcb640b016f0d29bf49 will fix the error you mention.
Travis just missed to rebuild after my update.

**Comment by cchampet** [comment]
Instead. So Travis did not build the right commit.
Can you fix the conflicts before I merge it?

**Comment by MarcAntoine-Arnaud** [comment]
Last commit was updated with this following list of Qt4 package list: http://packages.ubuntu.com/fr/trusty/amd64/libqt4-dev/filelist

**Pull request merged**
