### PR TITLE
Add complete-analyser app

### PR DESCRIPTION
**Pull request by cchampet**
The application is based on [avTranscoder library](https://github.com/avTranscoder/avTranscoder).
This is the first step to use loudness analyser / corrector with a more complex system to read given audio input.
If you have a better application name than "loudness-analyser-complete", go ahead!

### CODE REVIEW

**Comment by MarcAntoine-Arnaud** [comment]
media-loudness-analyser ?

**Comment by MarcAntoine-Arnaud** [comment]
Do you think it can be interesting to have the possibility to analyse one media essence, with multi programs (Stereo, Multichannel, VO/VF/AD/etc.) using only one process ?
Or maybe to complex to have it here ?
I think it's more usefull to pass a command line arguments like:
`media-loudness-analyser -i inputfile.mxf -p 1 2 -p 3 4 5 6 7 8`
(with --input and --program long options)
it will analyse for this file, first 2 channels for stereo, and 3 4 5 6 7 8 as a 5.1.
It was also possible to reorder here multichannels layout:
`media-loudness-analyser -i inputfile.mxf -p 1 2 -p 4 3 6 5 8 7`

**Comment by cchampet** [comment]
Yes 'media-loudness-analyser' is a better name!

Use several arguments instead of a configuration file is maybe easier for the user.
Our common case will be to extract one audio stream from several media files, and analyse the loudness with the audio mapping propose by the user. We need to have the possibility to extract more than one audio stream for each media too.
But I cannot find any case which corresponds to analyse one media essence, with multi programs (Stereo, Multichannel, VO/VF/AD/etc.) using only one process.

**Comment by cchampet** [comment]
The v1 of the app is ready to be merged.
One thing is missing: the possibility to analyse one media essence, with multi programs (Stereo, Multichannel, VO/VF/AD/etc.) using only one process. I will create an issue for that.
@MarcAntoine-Arnaud ?

**Pull request merged**
