### PR TITLE
Some refactoring

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**

### CODE REVIEW

**Comment by cchampet** [comment]
Great!
One more thing, I have a compilation error:
```
app/LoudnessValidator/PLoudProcess.hpp:4:49: fatal error: LoudnessAnalyser/LoudnessAnalyser.hpp: No such file or directory
```
It appears that you include several times *LoudnessAnalyser/LoudnessAnalyser.hpp* instead of *loudnessAnalyser/LoudnessAnalyser.hpp*.
@MarcAntoine-Arnaud  You did not have any errors like this one?

**Comment by MarcAntoine-Arnaud** [comment]
Ooo yep linux is case sensitive, not mac ...
I'll fix it.

**Comment by cchampet** [comment]
LGTM
@valnoel ?

**Comment by valnoel** [comment]
:+1:

**Pull request merged**
