### PR TITLE
[WIP] loudnessTools: fix how to find libsndfile

### PR DESCRIPTION
**Pull request by cchampet**

### CODE REVIEW

**Comment by cchampet** [comment]
Up to v1.0.0 ?

**Comment by valnoel** [comment]
Great! Could you update the INSTALL.md file before we update the version ?

**Comment by cchampet** [comment]
Yep the doc was updated here 04c468d

**Comment by valnoel** [comment]
May I ask something like adding a description of each libraries (and their purposes) in the _README_ file ? :D

**Comment by cchampet** [comment]
I think the description of libs and apps is done ;)

**Pull request merged**
